[model]
name = "DIFF-R"
transport = "retrograde"
parameter_sharing = "independent"

[data]
network = "paper-rf/data/striatum/network.csv"
observations = "paper-rf/data/striatum/observations.csv"

[seeding]
seed_indices = [74]
infer_seed = true

[inference]
n_chains = 1
target_acceptance = 0.65
sampler = "NUTS"
n_samples = 1000
n_warmup = 1000
mean_data = false

[holdout]
strategy = "none"
